
apiVersion: v1
kind: Service
metadata:
  annotations:
    konghq.com/override: {{ include "threadfix.provider.fullname" . }}-actuator-service
    konghq.com/plugins: jwt, tf-session
  labels:
    {{- include "threadfix.self.labels" . | nindent 4 }}
  name: {{ include "threadfix.provider.fullname" . }}-actuator-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 8095
    protocol: TCP
    targetPort: 8095
  selector:
    {{- include "threadfix.provider.selectorLabels" . | nindent 4 }}
