apiVersion: v1
kind: Service
metadata:
  annotations:
    konghq.com/override: {{ include "threadfix.queue.fullname" . }}-api-svc
    konghq.com/plugins: jwt, tf-session
  labels:
    {{- include "threadfix.self.labels" . | nindent 4 }}
  name: {{ include "threadfix.queue.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: {{ template "threadfix.queue.servicePort" . }}
    protocol: TCP
    targetPort: 9110
  selector:
    {{- include "threadfix.queue.selectorLabels" . | nindent 4 }}
