apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: api-unarchive
  namespace: {{ .Release.Namespace }}
proxy: {}
route:
  preserve_host: false
  protocols:
  - https
  regex_priority: 0
  strip_path: true

