apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: api-override
  namespace: {{ .Release.Namespace }}
proxy: {}
route:
  methods:
  - PATCH
  preserve_host: false
  protocols:
  - https
  regex_priority: 0
  strip_path: true

