apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: api-purge-assets
  namespace: {{ .Release.Namespace }}
proxy: {}
route:
  methods:
    - DELETE
  preserve_host: false
  protocols:
    - https
  regex_priority: 0
  strip_path: false

