apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "threadfix.self.labels" . | nindent 4 }}
  name: {{ include "threadfix.crud.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: {{ include "threadfix.crud.servicePort" . }}
    protocol: TCP
    targetPort: 8070
  selector:
    {{- include "threadfix.crud.selectorLabels" . | nindent 4 }}