apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crud-log-claim
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "threadfix.self.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M
