
apiVersion: v1
kind: Service
metadata:
  annotations:
    konghq.com/override: {{ include "threadfix.crud.fullname" . }}-report
    konghq.com/plugins: jwt, tf-session
  labels:
    {{- include "threadfix.self.labels" . | nindent 4 }}
  name: {{ include "threadfix.crud.fullname" . }}-report
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: {{ include "threadfix.crud.servicePort" . }}
    protocol: TCP
    targetPort: 8070
  selector:
    {{- include "threadfix.crud.selectorLabels" . | nindent 4 }}
