apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: {{ include "threadfix.crud.fullname" . }}-unarchive
  namespace: {{ .Release.Namespace }}
proxy:
  connect_timeout: 60000
  path: /unarchive
  protocol: http
  read_timeout: 60000
  retries: 5
  write_timeout: 60000

