apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "threadfix.appsec.fullname" . }}-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
