apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: {{ include "threadfix.appsec.fullname" . }}-rest
  namespace: {{ .Release.Namespace }}
proxy:
  connect_timeout: 60000
  path: /threadfix/rest
  protocol: http
  read_timeout: 60000
  retries: 5
  write_timeout: 60000
