
apiVersion: v1
kind: Service
metadata:
  annotations:
    konghq.com/override: {{ include "threadfix.appsec.fullname" . }}-core
    konghq.com/plugins: appsec-jwt, appsec-tf-session
  labels:
    {{- include "threadfix.self.labels" . | nindent 4 }}
  name: {{ include "threadfix.appsec.fullname" . }}-core
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ template "threadfix.appsec.servicePort" . }}
    protocol: TCP
    targetPort: 8080
  selector:
    {{- include "threadfix.appsec.selectorLabels" . | nindent 4 }}

