apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: {{ include "threadfix.appsec.fullname" . }}-core
  namespace: {{ .Release.Namespace }}
proxy:
  connect_timeout: 60000
  path: /threadfix
  protocol: http
  read_timeout: 60000
  retries: 5
  write_timeout: 60000