apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: threadfix
  namespace: {{ .Release.Namespace }}
proxy: {}
route:
  preserve_host: true
  protocols:
  - https
  regex_priority: 0
  strip_path: true
