apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: {{ include "threadfix.consecimporter.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
proxy:
  connect_timeout: 60000
  path: /consecimporter
  protocol: http
  read_timeout: 60000
  retries: 5
  write_timeout: 60000

