
apiVersion: v1
kind: Service
metadata:
  annotations:
    konghq.com/override: {{ include "threadfix.consecimporter.fullname" . }}-actuator-service
    konghq.com/plugins: jwt
  labels:
    {{- include "threadfix.self.labels" . | nindent 4 }}
  name: {{ include "threadfix.consecimporter.fullname" . }}-actuator-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: {{ template "threadfix.consecimporter.servicePort" . }}
    protocol: TCP
    targetPort: 8040
  selector:
    {{- include "threadfix.consecimporter.selectorLabels" . | nindent 4 }}
