apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "threadfix.kafka.cm" . }}
  namespace: {{ .Release.Namespace }}
data:
  advertised-listeners: {{ include "threadfix.kafka.advertised.listeners" . }}

