apiVersion: v1
kind: Service
metadata:
  name: {{ include "threadfix.auth.fullname" . }}
  labels:
    {{- include "threadfix.self.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ template "threadfix.auth.servicePort" . }}
      targetPort: 8050
      protocol: TCP
      name: http
  selector:
    {{- include "threadfix.auth.selectorLabels" . | nindent 4 }}
