
apiVersion: v1
kind: Service
metadata:
  annotations:
    konghq.com/override: {{ include "threadfix.auth.fullname" . }}-actuator-service
    konghq.com/plugins: jwt, tf-session
  labels:
    {{- include "threadfix.self.labels" . | nindent 4 }}
  name: {{ include "threadfix.auth.fullname" . }}-actuator-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: {{ template "threadfix.auth.servicePort" . }}
    protocol: TCP
    targetPort: 8050
  selector:
    {{- include "threadfix.auth.selectorLabels" . | nindent 4 }}
