apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "threadfix.auth.fullname" . }}
  labels:
    {{- include "threadfix.self.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- include "threadfix.self.progressDeadlineSeconds" . | nindent 2 }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "threadfix.auth.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ .Values.global.threadfix.featureToggles | toString | sha256sum }}
      labels:
        {{- include "threadfix.auth.selectorLabels" . | nindent 8 }}
    spec:
      {{ include "threadfix.imagePullSecrets" . | indent 6 }}
      serviceAccountName: {{ include "threadfix.self.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if eq "true" ( include "threadfix.wait.enabled" . ) }}
      initContainers:
        {{ include "threadfix.waitForDB" . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ template "threadfix.auth.fullname" . }}
          {{- $probeValues := dict }}
          {{- $_ := set $probeValues "livenessPath" "/actuator/health/liveness" }}
          {{- $_ := set $probeValues "readinessPath" "/actuator/health/readiness" }}
          {{- $_ := set $probeValues "port" "http" -}}
          {{- include "threadfix.probes" (dict "args" $probeValues "context" . ) | indent 10 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ template "threadfix.image" . }}
          imagePullPolicy: {{ template "threadfix.image.pullPolicy" . }}
          env:
            - name: api.gateway.host
              valueFrom:
                configMapKeyRef:
                  name: {{ template "threadfix.kong.cm" . }}
                  key: kong.admin.name
            - name: api.gateway.port
              valueFrom:
                configMapKeyRef:
                  name: {{ template "threadfix.kong.cm" . }}
                  key: kong.admin.port
            - name: LICENSE_LOCATION
              value: /opt/threadfix.license
            - name: LOGGING_CONFIG
              value: /opt/logback-all.xml
            - name: SPRING_DATASOURCE_DRIVER-CLASS-NAME
              value: "{{ template "threadfix.db.driver" . }}"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "threadfix.db.secret" . }}
                  key: password
            - name: SPRING_DATASOURCE_URL
              value: "{{ template "threadfix.appsec.db.url" . }}"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "threadfix.db.secret" . }}
                  key: username
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_GLOBALLY_QUOTED_IDENTIFIERS
              value: "{{ template "threadfix.db.globallyQuoted" . }}"
            - name: SPRING_PROFILES_ACTIVE
              value: {{ include "threadfix.springProfilesActive" . | quote }}
            - name: JAVA_TOOL_OPTIONS
              value: {{ .Values.javaOpts }} -Dorg.owasp.esapi.resources="/opt/threadfix/esapi"
            - name: SPRING_REDIS_HOST
              value: "{{ template "threadfix.redis.fullname" . }}-master"
            - name: SPRING_REDIS_PORT
              value: "{{ template "threadfix.redis.port" . }}"
            - name: SPRING_REDIS_TIMEOUT
              value: {{ .Values.redis.timeout | quote }}
            - name: SPRING_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "threadfix.redis.secret" . }}
                  key: redis-password
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config-flags
          ports:
            - name: http
              containerPort: 8050
              protocol: TCP
          workingDir: /app
          volumeMounts:
            - name: tf-config
              mountPath: /opt/logback-all.xml
              subPath: logback-all.xml
            - name: tf-license
              mountPath: /opt/threadfix.license
              subPath: threadfix.license
              readOnly: true
            - name: tf-config-secrets
              mountPath: /opt/threadfix/esapi/ESAPI.properties
              subPath: ESAPI.properties
              readOnly: true
            - name: tf-config-secrets
              mountPath: /opt/threadfix/esapi/validation.properties
              subPath: validation.properties
              readOnly: true
            - name: tf-config-secrets
              mountPath: /opt/saml/onelogin.saml.properties
              subPath: onelogin.saml.properties
              readOnly: true
            - name: working-dir
              mountPath: /app
            {{- if .Values.extraVolumeMounts }}
            {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
            {{- end }}  
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: tf-config
        configMap:
          name: {{ .Release.Name }}-config
      - name: tf-config-secrets
        secret:
          secretName: {{ template "threadfix.config.secrets" . }}
      - name: tf-license
        secret:
          secretName: {{ template "threadfix.license.cm" . }}
          items:
            - key: threadfix.license
              path: threadfix.license
      - name: working-dir
        emptyDir: {}
      {{- if .Values.extraVolumes }}
      {{- toYaml .Values.extraVolumes | nindent 6 }}
      {{- end }}

