
apiVersion: v1
kind: Service
metadata:
  annotations:
    konghq.com/override: {{ include "threadfix.websocket.fullname" . }}-svc
    konghq.com/plugins: jwt
  labels:
    {{- include "threadfix.self.labels" . | nindent 4 }}
  name: {{ include "threadfix.websocket.fullname" . }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: {{ template "threadfix.websocket.servicePort" . }}
    protocol: TCP
    targetPort: 8085
  selector:
    {{- include "threadfix.websocket.selectorLabels" . | nindent 4 }}
