apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "threadfix.self.labels" . | nindent 4 }}
  name: {{ template "threadfix.websocket.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: {{ template "threadfix.websocket.servicePort" . }}
    protocol: TCP
    targetPort: 8085
  selector:
    {{- include "threadfix.websocket.selectorLabels" . | nindent 4 }}

