{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" -}}
apiVersion: networking.k8s.io/v1
{{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  annotations:
    konghq.com/override: ui-ws
    kubernetes.io/ingress.class: {{ include "threadfix.ingress.class" . }}
  name: ui-ws
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - http:
      paths:
      - backend:
          {{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
          service:
            name: {{ include "threadfix.websocket.fullname" . }}-svc
            port:
              number: {{ include "threadfix.websocket.servicePort" . }}
        pathType: Prefix
          {{- else }}
          serviceName: {{ include "threadfix.websocket.fullname" . }}-svc
          servicePort: {{ include "threadfix.websocket.servicePort" . }}
          {{- end }}
        path: /ui/ws
