apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "threadfix.self.labels" . | nindent 4 }}
  name: {{ include "threadfix.websocket.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- include "threadfix.self.progressDeadlineSeconds" . | nindent 2 }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "threadfix.websocket.selectorLabels" . | nindent 6 }}
  strategy: {}
  template:
    metadata:
      annotations:
        checksum/config: {{ .Values.global.threadfix.featureToggles | toString | sha256sum }}
      creationTimestamp: null
      labels:
        {{- include "threadfix.websocket.selectorLabels" . | nindent 8 }}
    spec:
      {{ include "threadfix.imagePullSecrets" . | indent 6 }}
      serviceAccountName: {{ include "threadfix.self.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if eq "true" ( include "threadfix.wait.enabled" . ) }}
      initContainers:
        {{ include "threadfix.waitForKafka" . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ template "threadfix.websocket.fullname" . }}
          {{- $probeValues := dict }}
          {{- $_ := set $probeValues "livenessPath" "/actuator/health/liveness" }}
          {{- $_ := set $probeValues "readinessPath" "/actuator/health/readiness" }}
          {{- $_ := set $probeValues "port" "http" -}}
          {{- include "threadfix.probes" (dict "args" $probeValues "context" . ) | indent 10 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ template "threadfix.image" . }}
          imagePullPolicy: {{ template "threadfix.image.pullPolicy" .  }}
          env:
            - name: SPRING_CLOUD_STREAM_KAFKA_STREAMS_BINDER_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "threadfix.kafka.cm" . }}
                  key: advertised-listeners
            - name: SPRING_KAFKA_BOOTSTRAPSERVERS
              value: "{{ template "threadfix.kafka.fullname" . }}:{{ include "threadfix.kafka.externalPort" . }}"
            - name: SPRING_PROFILES_ACTIVE
              value: {{ include "threadfix.springProfilesActive" . | quote }}
            - name: JAVA_TOOL_OPTIONS
              value: {{ .Values.javaOpts | quote }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config-flags
          ports:
          - name: http
            containerPort: 8085
            protocol: TCP
          volumeMounts:
          - name: tf-config
            mountPath: /opt/logback-all.xml
            subPath: logback-all.xml
          {{- if .Values.extraVolumeMounts }}
          {{- toYaml .Values.extraVolumeMounts | nindent 10 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}  
      volumes:
      - name: tf-config
        configMap:
          name: {{ .Release.Name }}-config
      {{- if .Values.extraVolumes }}
      {{- toYaml .Values.extraVolumes | nindent 6 }}
      {{- end }}
