{{- $username := include "threadfix.db.username" . }}
{{- $password := include "threadfix.db.password" . }}
{{- if not ( or .Values.existingSecret .Values.global.threadfix.db.existingSecret ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "threadfix.db.secret" . }}
type: Opaque
data:
  username: {{ $username | b64enc | quote }}
  password: {{ $password | b64enc | quote}}

---

{{- if .Release.IsInstall }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "threadfix.db.secret" . }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
    "helm.sh/hook-weight": "-10"
type: Opaque
data:
  username: {{ $username | b64enc | quote }}
  password: {{ $password | b64enc | quote }}

{{- end -}}
{{- end -}}