apiVersion: v1
kind: Service
metadata:
  name: {{ template "threadfix.db.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "threadfix.self.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ template "threadfix.db.servicePort" . }}
  selector:
    {{- include "threadfix.db.selectorLabels" . | nindent 4 }}