apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: {{ .Release.Namespace }}
data:
  db-init: |
    CREATE DATABASE IF NOT EXISTS `threadfix` CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
    CREATE DATABASE IF NOT EXISTS `network` CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
    CREATE DATABASE IF NOT EXISTS `provider` CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

    GRANT ALL ON *.* TO '{{ include "threadfix.db.username" . }}'@'%';
  {{- if ( index .Values "mysqld.cnf" ) }}
  mysqld-cnf: {{ index .Values "mysqld.cnf" | quote }}
  {{- else }}
  mysqld-cnf: {{ .Files.Get "config/mysqld.cnf" | quote }}
  {{- end }}
  
