apiVersion: v1
kind: Service
metadata:
  name: {{ include "threadfix.zk.fullname" . }}-cs
  labels:
    {{- include "threadfix.self.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ template "threadfix.zk.clientPort" . }}
      name: client
  selector:
    {{- include "threadfix.zk.selectorLabels" . | nindent 4 }}