apiVersion: v1
kind: Service
metadata:
  name: {{ include "threadfix.zk.fullname" . }}-hs
  labels:
    {{- include "threadfix.self.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  ports:
    - port: 2888
      name: server
    - port: 3888
      name: leader-election
  selector:
    {{- include "threadfix.zk.selectorLabels" . | nindent 4 }}
