apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "threadfix.appsecdata.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  kafka.minPartionCount: {{ default .Values.kafka.minPartionCount .Values.global.threadfix.appsecdata.kafkaMinPartionCount | quote }}
  kafka.fileImporterPartitionCount: {{ default .Values.kafka.fileImporterPartitionCount .Values.global.threadfix.appsecdata.kafkaFileImporterPartitionCount | quote }}
  kafka.remoteProviderImporterPartitionCount: {{ default .Values.kafka.remoteProviderImporterPartitionCount .Values.global.threadfix.appsecdata.kafkaRemoteProviderImporterPartitionCount | quote }}