{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" -}}
apiVersion: networking.k8s.io/v1
{{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  annotations:
    konghq.com/override: actuator-importer
    kubernetes.io/ingress.class: {{ include "threadfix.ingress.class" . }}
  name: actuator-importer
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - http:
      paths:
      - backend:
          {{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
          service:
            name: {{ include "threadfix.importer.fullname" . }}-actuator-service
            port:
              number: {{ template "threadfix.importer.servicePort" . }}
        pathType: Prefix
          {{- else }}
          serviceName: {{ include "threadfix.importer.fullname" . }}-actuator-service
          servicePort: {{ template "threadfix.importer.servicePort" . }}
          {{- end }}
        path: /actuator/importer
