apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "threadfix.self.labels" . | nindent 4 }}
  name: {{ include "threadfix.importer.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: {{ template "threadfix.importer.servicePort" . }}
    protocol: TCP
    targetPort: 8060
  selector:
    {{- include "threadfix.importer.selectorLabels" . | nindent 4 }}

