apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: actuator-defect-api
  namespace: {{ .Release.Namespace }}
proxy: {}
route:
  methods:
  - GET
  preserve_host: false
  protocols:
  - https
  regex_priority: 0
  strip_path: true

