{{- if and .Values.networkPolicy.enabled .Values.appsecdata.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-allow-appsecdata
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
   matchLabels:
    {{ include "threadfix.appsecdata.selectorLabels" . | nindent 4 }}
  policyTypes:
    - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/instance: {{ .Release.Name }}
          app.kubernetes.io/part-of: {{ include "threadfix.name" . }}
    ports:
    - protocol: TCP
      port: 9107
{{- end -}}