{{ if not (index .Values "global" "threadfix" "configSecretsOverride" ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-config-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- if ( index .Values "ESAPI.properties" ) }}
  ESAPI.properties: {{ index .Values "ESAPI.properties" | b64enc }}
  {{- else }}
  ESAPI.properties: {{ include "threadfix.esapi.properties" . | b64enc }}
  {{- end }}
  {{- if ( index .Values "validation.properties" ) }}
  validation.properties: {{ index .Values "validation.properties" | b64enc }}
  {{- else }}
  validation.properties: {{ include "threadfix.esapi.validation.properties" . | b64enc }}
  {{- end }}
  {{- if ( index .Values "onelogin.saml.properties" ) }}
  onelogin.saml.properties: {{ index .Values "onelogin.saml.properties" | b64enc }}
  {{- else }}
  onelogin.saml.properties: {{ include "threadfix.onelogin.saml.properties" . | b64enc }}
  {{- end }}
{{- end -}}