apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config-flags
  namespace: {{ .Release.Namespace }}
data:
  {{- range $key, $val := .Values.global.threadfix.featureToggles}}
    {{- if hasPrefix "FEATURE_TOGGLES_" $key}}
      {{ $key }}: {{ $val | quote }}
    {{- end}}
  {{- end}}

  