{{- if and .Values.networkPolicy.enabled .Values.kong.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "threadfix.kong.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
   matchLabels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "threadfix.kong.name" . }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{ include "threadfix.appsec.selectorLabels" . | nindent 10 }}
    - podSelector:
        matchLabels:
          {{ include "threadfix.auth.selectorLabels" . | nindent 10 }}
    ports:
    - protocol: TCP
      port: {{ include "threadfix.kong.admin.port" . }}
  - from: []
    ports:
      - protocol: TCP
        port:  {{ .Values.kong.proxy.http.containerPort }}
      - protocol: TCP
        port: {{ .Values.kong.proxy.tls.containerPort }}
{{- end -}}