{{ if (index .Values "threadfix.license")}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "threadfix.license.cm" . }}
  namespace: {{ .Release.Namespace }}
data:
  threadfix.license: {{ index .Values "threadfix.license" | b64enc }}
{{- end -}}