{{- $password := include "threadfix.redis.password" . }}
apiVersion: v1
kind: Secret
metadata:
  name: tf-session-plugin-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  tf-session: |
    anonymous: null
    redis_host: {{ template "threadfix.redis.fullname" . }}-master
    redis_port: {{ template "threadfix.redis.port" . }}
    redis_password: {{ $password }}
    redis_timeout: 15000
  appsec-tf-session: |
    anonymous: anonymous
    redis_host: {{ template "threadfix.redis.fullname" . }}-master
    redis_port: {{ template "threadfix.redis.port" . }}
    redis_password: {{ $password }}
    redis_timeout: 15000
  redis-password: {{ $password }}