{{- if and .Values.networkPolicy.enabled .Values.ui.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-allow-ui
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
   matchLabels:
    {{ include "threadfix.ui.selectorLabels" . | nindent 4 }}
  policyTypes:
    - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/instance: {{ .Release.Name }}
    ports:
    - protocol: TCP
      port: 8080
{{- end -}}