{{- if and .Values.networkPolicy.enabled .Values.zk.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-allow-zk
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
   matchLabels:
    {{ include "threadfix.zk.selectorLabels" . | nindent 4 }}
  policyTypes:
    - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{ include "threadfix.kafka.selectorLabels" . | nindent 10 }}
    ports:
    - protocol: TCP
      port: {{ include "threadfix.zk.clientPort" . }}
  - from:
    - podSelector:
        matchLabels:
          {{ include "threadfix.zk.selectorLabels" . | nindent 10 }}
    ports:
    - protocol: TCP
      port: 2888
    - protocol: TCP
      port: 3888
{{- end -}}