apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "threadfix.appsecimporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  kafka.minPartionCount: {{ default .Values.kafka.minPartionCount .Values.global.threadfix.appsecimporter.kafkaMinPartionCount | quote }}
  kafka.maxProcessingTimeMS: {{ default .Values.kafka.maxProcessingTimeMS .Values.global.threadfix.appsecimporter.kafkaMaxProcessingTimeMS | quote }}