{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" -}}
apiVersion: networking.k8s.io/v1
{{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  annotations:
    konghq.com/override: root
    kubernetes.io/ingress.class: {{ include "threadfix.ingress.class" . }}
  name: root
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - http:
      paths:
      - backend:
          {{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
          service:
            name: {{ template "threadfix.self.fullname" . }}
            port:
              number: 80
        pathType: Prefix
          {{- else }}
          serviceName: {{ template "threadfix.self.fullname" . }}
          servicePort: 80
          {{- end }}
        path: /
