apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: {{ template "threadfix.ui.fullname" . }}
  namespace: {{ .Release.Namespace }}
proxy:
  connect_timeout: 60000
  protocol: http
  read_timeout: 60000
  retries: 5
  write_timeout: 60000

